"""Text normalisation.

Human CVs (scraped from a website) and AI CVs (generated by a local LLM) arrive in
very different *formats*: the AI ones use markdown, bullets and title-case headings,
the scraped ones use ALL-CAPS headings and odd spacing. If we left that in, a model
could reach ~100% accuracy just by spotting the formatting, and learn nothing about
writing style. This is called *shortcut learning*. `normalize` strips the format so
that both classes look the same and only the wording is left to learn from.
"""

from __future__ import annotations

import re

# Anonymisation placeholders used by the human dataset. The generator is asked to use
# the same ones, and we strip them from both classes so they can't act as a shortcut.
PLACEHOLDERS = [r"company name", r"city\s*,\s*state", r"\[[^\]]*\]"]
PLACEHOLDER_RE = re.compile("|".join(PLACEHOLDERS), re.IGNORECASE)

MARKDOWN_RE = re.compile(r"(\*\*|__|`|^#+\s*|^\s*[-*•●▪◦]\s+|^\s*\d+[.)]\s+)", re.MULTILINE)
WORD_RE = re.compile(r"[a-z]+(?:'[a-z]+)?")
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?;])\s+")


def normalize(text: str, max_words: int | None = None) -> str:
    """Lower-case, strip markdown/bullets/placeholders, collapse whitespace, truncate."""
    text = MARKDOWN_RE.sub(" ", text)
    text = PLACEHOLDER_RE.sub(" ", text)
    text = text.replace("–", "-")  # en dash -> hyphen (the em dash is kept: it's a style signal)
    text = re.sub(r"\s+", " ", text).strip().lower()
    if max_words:
        text = " ".join(text.split(" ")[:max_words])
    return text


def words(text: str) -> list[str]:
    return WORD_RE.findall(text.lower())


def sentences(text: str) -> list[str]:
    return [s for s in SENTENCE_SPLIT_RE.split(text) if words(s)]
